{
 "title": "HuaTuo 根因定位 AutoTracing 大盘",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": "{\"find\": \"terms\", \"field\": \"region\", \"size\": 100}"
   },
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"hostname\", \"query\": \"region:$region\", \"size\":20000}"
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "内核事件总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "cpuidle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:cpuidle AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "cpusys",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:cpusys AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "directreclaim",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:directreclaim AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "container loadavg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:ctnDLoad AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "dropwatch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:dropwatch AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "waitrate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:waitrate AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "hungtask",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:hungtask AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "memburst",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:memburst AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "oom",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:oom AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "softlockup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:softlockup AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "softirq",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:softirq AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "iotracer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:iotracer AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "netrecvlat",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:netrecvlat AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "netdev",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "((tracer_name:netdev_events AND (tracer_data.linkstatus:linkStatusCarrierDown OR tracer_data.linkstatus:linkStatusAdminDown)) OR tracer_name:lacp) AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "事件触发时间点",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "事件占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "cgroupusage",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:cgroupusage AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "cpusys",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:cpusys AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "directreclaim",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:directreclaim AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "ctnDLoad",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:ctnDLoad AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "dropwatch",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:dropwatch AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "hungtask",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:hungtask AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "iotracer",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:iotracer AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "memburst",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:memburst AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "netrecvlat",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:netrecvlat AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "oom",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:oom AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "softirq",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:softirq AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "softlockup",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:softlockup AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    },
    {
     "alias": "waitrateitle",
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:waitrateitle AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  { "title": "cpuidle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "cpuidle阈值说明",
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 21 },
   "options": {
    "content": "触发条件：\n\n1、sys > 45%   \n2、user > 75% && user 单位时间(10s)波动 > 30%  \n3、usage > 90% && usage单位时间(10s)波动 > 30%  \n以上条件符合其中一"
   }
  },
  {
   "title": "cpuidle",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:cpuidle AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "cpuidle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:cpuidle AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "cpuidle",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "100" }, "type": "raw_data" }
     ],
     "query": "tracer_name:cpuidle AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  { "title": "cpusys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "cpusys阈值说明",
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 41 },
   "options": {
    "content": "触发条件：   \n1、sys > 50%  \n2、sys单位时间(1s)波动 > 30%   \n以上条件符合其中一"
   }
  },
  {
   "title": "cpusys",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:cpusys AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "cpusys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:cpusys AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "cpusys",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "tracer_name:cpusys AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  { "title": "directreclaim", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "directreclaim阈值说明",
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 61 },
   "options": {
    "content": "触发条件：   \n1、1s的数据抓取时间中，进程在sys态停留累计超过900ms   \n// 由于sys态非抢占，所以有的进程时间要长于1s\n"
   }
  },
  {
   "title": "directreclaim",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:directreclaim AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "directreclaim",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 61 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tracer_name:directreclaim AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "directreclaim",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "tracer_name:directreclaim AND region:$region AND hostname:$hostname",
     "timeField": "uploaded_time"
    }
   ]
  },
  {
   "title": "loadavg",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    { "title": "loadavg", "type": "text", "gridPos": { "h": 9, "w": 4, "x": 0, "y": 213 }, "options": { "content": "触发条件：\n" } },
    {
     "title": "loadavg",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 213 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:ctnDLoad AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "loadavg",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 213 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:ctnDLoad AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "loadavg",
     "type": "table",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 222 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:ctnDLoad AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "loadavg",
     "type": "logs",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 222 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:ctnDLoad AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "dropwatch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "dropwatch阈值说明",
     "type": "text",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 232 },
     "options": {
      "content": "丢包触发条件：\n- TCP 请求 && TCP 状态非 CLOSED\n\n已排除如下场景：\n1. TCP CLOSE_WAIT 状态中的 ooo\n```text\n// state: CLOSE_WAIT\n// stack:\n//  1. kfree_skb/ffffffff963047b0\n//  2. kfree_skb/ffffffff963047b0\n//  3. skb_rbtree_purge/ffffffff963089e0\n//  4. tcp_fin/ffffffff963ac200\n//  5. ...\n```"
     }
    },
    {
     "title": "dropwatch",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 232 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:dropwatch AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "dropwatch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 232 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:dropwatch AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "dropwatch",
     "type": "table",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 241 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:dropwatch AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "dropwatch",
     "type": "logs",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 241 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:dropwatch AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "hungtask",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    { "title": "hungtask阈值说明", "type": "text", "gridPos": { "h": 9, "w": 4, "x": 0, "y": 233 }, "options": { "content": "系统存在hungtask" } },
    {
     "title": "hungtask",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 233 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:hungtask AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "hungtask",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 233 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:hungtask AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "hungtask",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 242 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
       ],
       "query": "tracer_name:hungtask AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "hungtask",
     "type": "logs",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 242 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:hungtask AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "iotracer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "iotracer阈值说明",
     "type": "text",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 237 },
     "options": {
      "content": "触发条件：\n- 机械盘, SATA SSD：\n    (1) io.util 持续多长时间超过 90%，持续时间超过2秒\n    (2) 2秒平均 IO 延迟大于 100ms\n- NVMe ssd:\n    (1)io.util 持续超过 90% && IO 带宽 >  (read:2000MB/s or write:1500MB/s)\n    (2) 2秒平均IO延迟大于100ms\n\n1和2是或的关系，有一个满足就会触发"
     }
    },
    {
     "title": "iotracer",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 237 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:iotracer AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "iotracer",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 237 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:iotracer AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "iotracer",
     "type": "table",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 246 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:iotracer AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "iotracer",
     "type": "logs",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 246 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:iotracer AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "memburst",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "memburst阈值说明",
     "type": "text",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 253 },
     "options": {
      "content": "内存在最近五分钟内变为两倍\n且\n当前宿主机匿名页占用达到70%"
     }
    },
    {
     "title": "memburst",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 253 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:memburst AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "memburst",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 253 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:memburst AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "memburst",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 262 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:memburst AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "netrecvlat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "netrecvlat阈值说明",
     "type": "text",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 254 },
     "options": {
      "content": "网络收方向延迟 事件触发条件(or)：\n- 1、网卡 -> 驱动收 > 5ms\n- 2、网卡 -> 协议栈收 > 10ms\n- 3、网卡 -> 用户态拷贝数据 > 115ms\n\n事件几乎都来自 3 (用户主动读取数据的时间超过了阈值)。\n\n过滤延迟发生的位置 where\n- 1 TO_NETIF_RCV\n- 2 TO_TCPV4_RCV\n- 3 TO_USER_COPY"
     }
    },
    {
     "title": "netrecvlat",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 5, "y": 254 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:netrecvlat AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "netrecvlat",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 254 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "tracer_name:netrecvlat AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "netrecvlat",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 263 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "5000" }, "type": "raw_data" }
       ],
       "query": "tracer_name:netrecvlat AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "netrecvlat",
     "type": "logs",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 263 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "5000" }, "type": "raw_data" }
       ],
       "query": "tracer_name:netrecvlat AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "oom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    { "title": "oom阈值说明", "type": "text", "gridPos": { "h": 9, "w": 4, "x": 0, "y": 237 }, "options": { "content": "系统或容器发生了oom" } },
    {
     "title": "oom",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 237 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:oom AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "oom",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 237 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:oom AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "oom",
     "type": "table",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 246 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "5000" }, "type": "raw_data" }
       ],
       "query": "tracer_name:oom AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "oom",
     "type": "logs",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 246 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:oom AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "softirq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    { "title": "softirq阈值说明", "type": "text", "gridPos": { "h": 9, "w": 4, "x": 0, "y": 256 }, "options": { "content": "软中断被关闭时长 > 100ms" } },
    {
     "title": "softirq",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 256 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:softirq AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "softirq",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 256 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:softirq AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "softirq",
     "type": "table",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 265 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:softirq AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "softirq",
     "type": "logs",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 265 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:softirq AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "softlockup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    { "title": "softlockup阈值说明", "type": "text", "gridPos": { "h": 9, "w": 4, "x": 0, "y": 223 }, "options": { "content": "系统发生softlockup" } },
    {
     "title": "softlockup",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 223 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:softlockup AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "softlockup",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 223 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:softlockup AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "softlockup",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 232 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:softlockup AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "softlockup",
     "type": "logs",
     "gridPos": { "h": 9, "w": 20, "x": 4, "y": 232 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:softlockup AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "waitrate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "waitrate阈值说明",
     "type": "text",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 222 },
     "options": {
      "content": "每个容器对近30分钟的waitrate率计算出均值mean和标准差std，如果当前的waitrate大于mean+std*factor则报警\n0级、新1、新2级的factor分别为30,40,60"
     }
    },
    {
     "title": "waitrate",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 222 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:waitrate AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "waitrate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 222 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:waitrate AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "waitrate",
     "type": "table",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 231 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:waitrate AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "waitrateitle",
     "type": "logs",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 231 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:waitrate AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  },
  {
   "title": "netdev",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Carrier Down",
     "type": "stat",
     "gridPos": { "h": 14, "w": 3, "x": 0, "y": 223 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:netdev_events AND tracer_data.linkstatus:linkStatusCarrierDown AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "网卡Down（物理层 Carrier Down）",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 3, "y": 223 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:netdev_events AND tracer_data.linkstatus:linkStatusCarrierDown AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "details",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 3, "y": 229 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:netdev_events AND tracer_data.linkstatus:linkStatusCarrierDown AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "Admin Down",
     "type": "stat",
     "gridPos": { "h": 13, "w": 3, "x": 0, "y": 237 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:netdev_events AND tracer_data.linkstatus:linkStatusAdminDown AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "网卡Down（管理 Admin Down）",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 3, "y": 237 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:netdev_events AND tracer_data.linkstatus: linkStatusAdminDown AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "details",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 3, "y": 243 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:netdev_events AND tracer_data.linkstatus: linkStatusAdminDown AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "lacp",
     "type": "stat",
     "gridPos": { "h": 13, "w": 3, "x": 0, "y": 250 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:lacp AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "聚合网卡 lacp 异常",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 3, "y": 250 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "uploaded_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "tracer_name:lacp AND region:$region AND hostname:$hostname",
       "timeField": "uploaded_time"
      }
     ]
    },
    {
     "title": "details",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 3, "y": 255 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "tracer_name:lacp AND region:$region AND hostname:$hostname&size=100",
       "timeField": "uploaded_time"
      }
     ]
    }
   ]
  }
 ]
}