{
 "title": "Metric 大盘 - 宿主机视图",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(huatuo_bamai_cpu_util_usr, region)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(huatuo_bamai_cpu_util_usr{region=~\"$region\"},host)"
    }
   },
   { "name": "metric", "label": "metric", "query": { "query": "metrics(huatuo_bamai_)" } }
  ]
 },
 "panels": [
  {
   "title": "宿主机容器列表($host)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_util_container_usr{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "指标：$metric",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$metric{host=~\"$host\"}",
     "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "宿主机磁盘q2c延迟超过20ms的IO个数统计（5分钟增量）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(huatuo_bamai_iolatency_disk_q2c{host=~\"$host\"}[5m])",
     "legendFormat": "{{host}},disk={{disk}} [{{latency}}]"
    }
   ]
  },
  {
   "title": "宿主机磁盘d2c延迟超过20ms的IO个数统计（5分钟增量）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "increase(huatuo_bamai_iolatency_disk_d2c{host=~\"$host\"}[5m])",
     "legendFormat": "{{host}},disk={{disk}} [{{latency}}]"
    }
   ]
  },
  {
   "title": "宿主机磁盘RAID flush延迟超过20ms的IO个数统计（5分钟增量）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase(huatuo_bamai_iolatency_disk_flush{host=~\"$host\"}[5m])",
     "legendFormat": "{{host}},disk={{disk}} [{{latency}}]"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "$host全局直接回收（累计值）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_vmstat_pgsteal_direct{host=~\"$host\"}/256",
     "legendFormat": "{{host}}/{{container_host}}"
    }
   ]
  },
  {
   "title": "$host kswapd回收（累计值）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_vmstat_pgsteal_kswapd{host=~\"$host\"}/256",
     "legendFormat": "{{host}}/{{container_host}}"
    }
   ]
  },
  {
   "title": "$host 脏页量（实时值）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_vmstat_nr_dirty{host=~\"$host\"}/256",
     "legendFormat": "{{host}}/{{container_host}}"
    }
   ]
  },
  {
   "title": "$host 正在回写的量（实时值）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_vmstat_nr_writeback{host=~\"$host\"}/256",
     "legendFormat": "{{host}}/{{container_host}}"
    }
   ]
  },
  {
   "title": "$host 空闲页面量（实时值）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_vmstat_nr_free_pages{host=~\"$host\"}/256",
     "legendFormat": "{{host}}/{{container_host}}"
    }
   ]
  },
  {
   "title": "$host page cache（实时值）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_vmstat_nr_inactive_file{host=~\"$host\"}/256 + huatuo_bamai_vmstat_nr_active_file{host=~\"$host\"}/256",
     "legendFormat": "{{host}}/{{container_host}}"
    }
   ]
  },
  {
   "title": "$host 匿名页（含shmem）（实时值）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_vmstat_nr_inactive_anon{host=~\"$host\"}/256 + huatuo_bamai_vmstat_nr_active_anon{host=~\"$host\"}/256",
     "legendFormat": "{{host}}/{{container_host}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "宿主机usr",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_util_usr{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "宿主机sys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_util_sys{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "容器usr",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_util_container_usr{host=~\"$host\"}",
     "legendFormat": "{{host}}/{{container_host}}/{{container_name}}:{{container_type}}"
    }
   ]
  },
  {
   "title": "容器sys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_util_container_sys{host=~\"$host\"}",
     "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
    }
   ]
  },
  {
   "title": "容器外部争抢",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_stat_container_exter_wait_rate{host=~\"$host\"}",
     "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
    }
   ]
  },
  {
   "title": "容器内部争抢",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_stat_container_inner_wait_rate{host=~\"$host\"}",
     "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
    }
   ]
  },
  {
   "title": "容器throttle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_stat_container_throttle_wait_rate{host=~\"$host\"}",
     "legendFormat": "{{host}}/{{container_host}}/{{container_name}}:{{container_type}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 } },
  {
   "title": "receive_bytes_total(Byte/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_container_receive_bytes_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{container_host}}/{{device}}"
    }
   ]
  },
  {
   "title": "receive_packets_total(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_receive_packets_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{host}}/{{device}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_container_receive_packets_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "transmit_bytes_total(Byte/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_transmit_bytes_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{host}}/{{device}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_container_transmit_bytes_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "transmit_packets_total(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_transmit_packets_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{host}}/{{device}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_container_transmit_packets_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "接收方向异常统计(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_receive_dropped_total{host=~\"$host\"}[30s])",
     "legendFormat": "dropped: {{device}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_receive_errors_total{host=~\"$host\"}[30s])",
     "legendFormat": "errors: {{device}}"
    }
   ]
  },
  {
   "title": "发送方向异常统计(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_transmit_dropped_total{host=~\"$host\"}[30s])",
     "legendFormat": "dropped: {{device}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_transmit_errors_total{host=~\"$host\"}[30s])",
     "legendFormat": "errors: {{device}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_transmit_carrier_total{host=~\"$host\"}[30s])",
     "legendFormat": "carrier: {{device}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_transmit_colls_total{host=~\"$host\"}[30s])",
     "legendFormat": "colls: {{device}}"
    }
   ]
  },
  {
   "title": "qdisc_bytes_total(MiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_qdisc_bytes_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{device}}/{{kind}}"
    }
   ]
  },
  {
   "title": "qdisc_packets_total(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_qdisc_packets_total{host=~\"$host\"}[30s])",
     "legendFormat": "{{device}}/{{kind}}"
    }
   ]
  },
  {
   "title": "QDisc 异常统计(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_qdisc_drops_total{host=~\"$host\"}[30s])",
     "legendFormat": "drops: {{device}}/{{kind}}"
    },
    {
     "expr": "rate(huatuo_bamai_qdisc_overlimits_total{host=~\"$host\"}[30s])",
     "legendFormat": "overlimits: {{device}}/{{kind}}"
    },
    {
     "expr": "rate(huatuo_bamai_qdisc_requeues_total{host=~\"$host\"}[30s])",
     "legendFormat": "requeues: {{device}}/{{kind}}"
    },
    {
     "expr": "rate(huatuo_bamai_qdisc_backlog{host=~\"$host\"}[30s])",
     "legendFormat": "backlog: {{device}}/{{kind}}"
    }
   ]
  },
  {
   "title": "arp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_arp_total{host=~\"$host\"}",
     "legendFormat": "Total:"
    },
    {
     "expr": "huatuo_bamai_arp_entries{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "huatuo_bamai_arp_container_entries{host=~\"$host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "TCP inuse(sockets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_TCP_inuse{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "huatuo_bamai_sockstat_container_TCP_inuse{host=~\"$host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "TCP tw(sockets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 272 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_TCP_tw{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "huatuo_bamai_sockstat_container_TCP_tw{host=~\"$host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "all sockets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_sockets_used{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "huatuo_bamai_sockstat_container_sockets_used{host=~\"$host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "TCP mem_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 290 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_TCP_mem_bytes{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "UDP mem_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 299 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_UDP_mem_bytes{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "UDP inuse(sockets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 308 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_UDP_inuse{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "huatuo_bamai_sockstat_container_UDP_inuse{host=~\"$host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "netstat 指标",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 317 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_InSegs{host=~\"$host\"}[30s])",
     "legendFormat": "InSegs"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_OutSegs{host=~\"$host\"}[30s])",
     "legendFormat": "OutSegs"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPDelivered{host=~\"$host\"}[30s])",
     "legendFormat": "TCPDelivered"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPOrigDataSent{host=~\"$host\"}[30s])",
     "legendFormat": "TCPOrigDataSent"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_ActiveOpens{host=~\"$host\"}[30s])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "huatuo_bamai_netstat_Tcp_CurrEstab{host=~\"$host\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_PassiveOpens{host=~\"$host\"}[30s])",
     "legendFormat": "PassiveOpens"
    }
   ]
  },
  {
   "title": "netstat 丢包",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 326 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_ListenDrops{host=~\"$host\"}[30s])",
     "legendFormat": "ListenDrops"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_ListenOverflows{host=~\"$host\"}[30s])",
     "legendFormat": "ListenOverflows"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPReqQFullDoCookies{host=~\"$host\"}[30s])",
     "legendFormat": "TCPReqQFullDoCookies"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_PFMemallocDrop{host=~\"$host\"}[30s])",
     "legendFormat": "PFMemallocDrop"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPBacklogDrop{host=~\"$host\"}[30s])",
     "legendFormat": "TCPBacklogDrop"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPRcvQDrop{host=~\"$host\"}[30s])",
     "legendFormat": "TCPRcvQDrop"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPTimeouts{host=~\"$host\"}[30s])",
     "legendFormat": "TCPTimeouts"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPLossFailures{host=~\"$host\"}[30s])",
     "legendFormat": "TCPLossFailures"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPSACKDiscard{host=~\"$host\"}[30s])",
     "legendFormat": "TCPSACKDiscard"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPMemoryPressures{host=~\"$host\"}[30s])",
     "legendFormat": "TCPMemoryPressures"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPMinTTLDrop{host=~\"$host\"}[30s])",
     "legendFormat": "TCPMinTTLDrop"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPMinTTLDrop{host=~\"$host\"}[30s])",
     "legendFormat": "TCPMinTTLDrop"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPTimeWaitOverflow{host=~\"$host\"}[30s])",
     "legendFormat": "TCPTimeWaitOverflow"
    }
   ]
  },
  {
   "title": "netstat 错误",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 335 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_InErrs{host=~\"$host\"}[30s])",
     "legendFormat": "InErrs"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_InCsumErrors{host=~\"$host\"}[30s])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPAbortOnMemory{host=~\"$host\"}[30s])",
     "legendFormat": "TCPAbortOnMemory"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPAbortOnTimeout{host=~\"$host\"}[30s])",
     "legendFormat": "TCPAbortOnTimeout"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPRetransFail{host=~\"$host\"}[30s])",
     "legendFormat": "TCPRetransFail"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPSackFailures{host=~\"$host\"}[30s])",
     "legendFormat": "TCPSackFailures"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPSackFailures{host=~\"$host\"}[30s])",
     "legendFormat": "TCPSackRecoveryFail"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_SyncookiesFailed{host=~\"$host\"}[30s])",
     "legendFormat": "SyncookiesFailed"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPWqueueTooBig{host=~\"$host\"}[30s])",
     "legendFormat": "TCPWqueueTooBig"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_AttemptFails{host=~\"$host\"}[30s])",
     "legendFormat": "AttemptFails"
    }
   ]
  },
  {
   "title": "netstat 重传",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 344 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_RetransSegs{host=~\"$host\"}[30s])",
     "legendFormat": "RetransSegs"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPSynRetrans{host=~\"$host\"}[30s])",
     "legendFormat": "TCPSynRetrans"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPFastRetrans{host=~\"$host\"}[30s])",
     "legendFormat": "TCPFastRetrans"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPSlowStartRetrans{host=~\"$host\"}[30s])",
     "legendFormat": "TCPSlowStartRetrans"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPSpuriousRTOs{host=~\"$host\"}[30s])",
     "legendFormat": "TCPSpuriousRTOs"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPSpuriousRtxHostQueues{host=~\"$host\"}[30s])",
     "legendFormat": "TCPSpuriousRtxHostQueues"
    }
   ]
  },
  {
   "title": "netstat 缓冲不足导致的丢包",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 353 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_PruneCalled{host=~\"$host\"}[30s])",
     "legendFormat": "PruneCalled"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_RcvPruned{host=~\"$host\"}[30s])",
     "legendFormat": "RcvPruned"
    }
   ]
  },
  {
   "title": "TCP SYN 包全量统计（包括接收/发送/重传）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 362 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_ActiveOpens{host=~\"$host\"}[30s])+rate(huatuo_bamai_netstat_TcpExt_TCPSynRetrans{host=~\"$host\"}[30s])+rate(huatuo_bamai_netstat_Tcp_PassiveOpens{host=~\"$host\"}[30s])+rate(huatuo_bamai_netstat_TcpExt_ListenDrops{host=~\"$host\"}[30s])",
     "legendFormat": "总量: {{host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_ActiveOpens{host=~\"$host\"}[30s])",
     "legendFormat": "发送端: {{host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_Tcp_PassiveOpens{host=~\"$host\"}[30s])+rate(huatuo_bamai_netstat_TcpExt_ListenDrops{host=~\"$host\"}[30s])",
     "legendFormat": "接收端: {{host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_TcpExt_TCPSynRetrans{host=~\"$host\"}[30s])",
     "legendFormat": "重传数（发+收）: {{host}}"
    }
   ]
  },
  {
   "title": "XFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 371 },
   "collapsed": true,
   "panels": [
    {
     "title": "碎片化程度 （平均 blocks/extent 每秒）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "increase(huatuo_bamai_xfs_alloc_blocks_total{host=~\"$host\"}[5m]) / clamp_min(increase(huatuo_bamai_xfs_alloc_extents_total{host=~\"$host\"}[5m]), 1e-6)",
       "legendFormat": "{{host}}，device={{device}}"
      }
     ]
    },
    {
     "title": "Inode cache 命中率（5m 平均每秒）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "clamp_min((increase(huatuo_bamai_xfs_inode_attempts_total{host=~\"$host\"}[5m]) - increase(huatuo_bamai_xfs_inode_missed_total{host=~\"$host\"}[5m]))/clamp_min(increase(huatuo_bamai_xfs_inode_attempts_total{host=~\"$host\"}[5m]), 1e-6),0)",
       "legendFormat": "{{host}}，device={{device}}"
      }
     ]
    },
    {
     "title": "Buffer 锁竞争等待次数（times/s）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(huatuo_bamai_xfs_buf_locked_waited_total{host=~\"$host\"}[30s])",
       "legendFormat": "{{host}}，device={{device}}"
      }
     ]
    },
    {
     "title": "Buffer 获取时繁忙次数（times/s）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(huatuo_bamai_xfs_buf_busy_locked_total{host=~\"$host\"}[30s])",
       "legendFormat": "{{host}}，device={{device}}"
      }
     ]
    },
    {
     "title": "Xlog 剩余空闲空间（bytes）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "huatuo_bamai_xfs_log_free_bytes{host=~\"$host\"}",
       "legendFormat": "{{host}}，device={{device}}"
      }
     ]
    },
    {
     "title": "Xlog 空间不足导致的进程睡眠次数（times/s）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "rate(huatuo_bamai_xfs_log_space_sleep_total{host=~\"$host\"}[30s])",
       "legendFormat": "{{host}}，device={{device}}"
      }
     ]
    }
   ]
  },
  { "title": "huatuo-bamai agent运行时指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 372 } },
  {
   "title": "huatuo-bamai memory vss(只显示前20个)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 373 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "topk(20, huatuo_bamai_runtime_memory_vss{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "huatuo-bamai memory rss(只展示前20个)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 381 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "topk(20,huatuo_bamai_runtime_memory_rss{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "huatuo-bamai cgroup RSS(只展示前20个)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 388 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "topk(20,huatuo_bamai_runtime_memory_cgroup_rss{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "huatuo-bamai sys cpu(只展示前20个)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 396 },
   "targets": [
    {
     "expr": "topk(20,huatuo_bamai_runtime_cpu_sys{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "huatuo-bamai user cpu(只展示前20个)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 404 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20,huatuo_bamai_runtime_cpu_user{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}