{
 "title": "Metric 大盘 - 容器视图",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(huatuo_bamai_cpu_util_usr, region)"
    }
   },
   {
    "name": "ns",
    "label": "ns",
    "query": {
     "query": "label_values(huatuo_bamai_cpu_util_container_usr{region=~\"$region\"},container_hostnamespace)"
    }
   },
   {
    "name": "container_host",
    "label": "container_host",
    "query": {
     "query": "label_values(huatuo_bamai_cpu_util_container_usr{container_hostnamespace=~\"$ns\"},container_host)"
    }
   },
   { "name": "metric", "label": "metric", "query": { "query": "metrics(huatuo_bamai_)" } }
  ]
 },
 "panels": [
  {
   "title": "指标：$metric",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "$metric{container_host=\"$container_host\", container_type != \"sidecar\"}",
     "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "容器访问磁盘q2c延迟超过20ms的IO个数统计（5分钟增量）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(huatuo_bamai_iolatency_container_q2c{container_hostNamespace=~\"$ns\"}[5m])",
     "legendFormat": "{{container_host}} [{{latency}}]"
    }
   ]
  },
  {
   "title": "容器访问磁盘d2c延迟超过20ms的IO个数统计（5分钟增量）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(huatuo_bamai_iolatency_container_d2c{container_hostNamespace=~\"$ns\"}[5m])",
     "legendFormat": "{{container_host}} [{{latency}}]"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$container_host 异步回收耗时(ms)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "huatuo_bamai_memory_others_container_asyncreclaim_time{container_host=~\"$container_host\"}/1000000",
       "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
      }
     ]
    },
    {
     "title": "$container_host try_charge 直接回收耗时",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "huatuo_bamai_memory_others_container_directstall_time{container_host=~\"$container_host\"}",
       "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
      }
     ]
    },
    {
     "title": "$container_host 异步回收量（累计值）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huatuo_bamai_memory_stat_container_pgsteal_cswapd{container_host=~\"$container_host\"}/1024/1024",
       "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
      }
     ]
    },
    {
     "title": "宿主直接回收和 try_charge 对 $container_host 直接回收的总量（累计值）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huatuo_bamai_memory_stat_container_pgsteal_direct{container_host=~\"$container_host\"}",
       "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
      }
     ]
    },
    {
     "title": "宿主kswapd和容器cswapd 对 $container_host 的异步回收的总量（累计值）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huatuo_bamai_memory_stat_container_pgsteal_kswapd{container_host=~\"$container_host\"}",
       "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
      }
     ]
    },
    {
     "title": "宿主直接回收对 $container_host 容器的回收量(累计值)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huatuo_bamai_memory_stat_container_pgsteal_globaldirect{container_host=~\"$container_host\"}",
       "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
      }
     ]
    },
    {
     "title": "宿主kswapd回收对 $container_host 容器的回收量(累计值)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "huatuo_bamai_memory_stat_container_pgsteal_globalkswapd{container_host=~\"$container_host\"}",
       "legendFormat": "{{host}}/{{container_host}}:{{container_type}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "容器usr",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_util_container_usr{container_host=~\"$container_host\", container_type != \"sidecar\"}",
     "legendFormat": "{{host}}/{{container_host}}: {{container_type}}"
    }
   ]
  },
  {
   "title": "容器sys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_util_container_sys{container_host=~\"$container_host\", container_type != \"sidecar\"}",
     "legendFormat": "{{host}}/{{container_host}}: {{container_type}}"
    }
   ]
  },
  {
   "title": "容器内部争抢",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_stat_container_inner_wait_rate{container_host=~\"$container_host\", container_type != \"sidecar\"}",
     "legendFormat": "{{host}}/{{container_host}}: {{container_type}}"
    }
   ]
  },
  {
   "title": "容器外部争抢",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_stat_container_exter_wait_rate{container_host=~\"$container_host\", container_type != \"sidecar\"}",
     "legendFormat": "{{host}}/{{container_host}}: {{container_type}}"
    }
   ]
  },
  {
   "title": "容器throttle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "huatuo_bamai_cpu_stat_container_throttle_wait_rate{container_host=~\"$container_host\", container_type != \"sidecar\"}",
     "legendFormat": "{{host}}/{{container_host}}: {{container_type}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "receive_bytes_total(Byte/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_container_receive_bytes_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "receive_packets_total(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_container_receive_packets_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "transmit_bytes_total(Byte/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_container_transmit_bytes_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "transmit_packets_total(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_container_transmit_packets_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "接收方向异常统计(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_container_receive_dropped_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "dropped: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_container_receive_errors_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "errors: {{container_host}}"
    }
   ]
  },
  {
   "title": "发送方向异常统计(packets/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netdev_container_transmit_dropped_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "dropped: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_container_transmit_errors_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "errors: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_contianer_transmit_carrier_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "carrier: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netdev_container_transmit_colls_total{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "colls: {{container_host}}"
    }
   ]
  },
  {
   "title": "arp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_arp_container_entries{container_host=~\"$container_host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "TCP inuse(sockets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_container_TCP_inuse{container_host=~\"$container_host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "TCP tw(sockets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_container_TCP_tw{container_host=~\"$container_host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "容器socket总量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huatuo_bamai_sockstat_container_sockets_used{container_host=~\"$container_host\"}",
     "legendFormat": "{{container_host}}"
    }
   ]
  },
  {
   "title": "netstat 指标",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_InSegs{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "InSegs: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_OutSegs{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "OutSegs: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPDelivered{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPDelivered: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPOrigDataSent{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPOrigDataSent: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_ActiveOpens{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "ActiveOpens: {{container_host}}"
    },
    {
     "expr": "huatuo_bamai_netstat_container_Tcp_CurrEstab{container_host=~\"$container_host\"}",
     "legendFormat": "CurrEstab: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_PassiveOpens{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "PassiveOpens: {{container_host}}"
    }
   ]
  },
  {
   "title": "netstat 丢包",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_ListenDrops{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "ListenDrops: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_ListenOverflows{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "ListenOverflows: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPReqQFullDoCookies{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPReqQFullDoCookies: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_PFMemallocDrop{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "PFMemallocDrop: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPBacklogDrop{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPBacklogDrop: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPRcvQDrop{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPRcvQDrop: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPTimeouts{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPTimeouts: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPLossFailures{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPLossFailures: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPSACKDiscard{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPSACKDiscard: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPMemoryPressures{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPMemoryPressures: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPMinTTLDrop{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPMinTTLDrop: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPMinTTLDrop{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPMinTTLDrop: {{container_host}}/{{container_name}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPTimeWaitOverflow{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPTimeWaitOverflow: {{container_host}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "netstat 错误",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_InErrs{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "InErrs: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_InCsumErrors{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "InCsumErrors: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPAbortOnMemory{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPAbortOnMemory: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPAbortOnTimeout{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPAbortOnTimeout: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPRetransFail{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPRetransFail: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPSackFailures{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPSackFailures: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPSackFailures{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPSackRecoveryFail: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_SyncookiesFailed{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "SyncookiesFailed: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPWqueueTooBig{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPWqueueTooBig: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_AttemptFails{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "AttemptFails: {{container_host}}"
    }
   ]
  },
  {
   "title": "netstat 重传",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_RetransSegs{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "RetransSegs: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPSynRetrans{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPSynRetrans: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPFastRetrans{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPFastRetrans: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPSlowStartRetrans{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPSlowStartRetrans: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPSpuriousRTOs{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPSpuriousRTOs: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_TCPSpuriousRtxHostQueues{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "TCPSpuriousRtxHostQueues: {{container_host}}"
    }
   ]
  },
  {
   "title": "netstat 因缓存区不足导致丢包",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_PruneCalled{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "PruneCalled: {{container_host}}"
    },
    {
     "expr": "rate(huatuo_bamai_netstat_container_TcpExt_RcvPruned{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "RcvPruned: {{container_host}}"
    }
   ]
  },
  {
   "title": "TCP SYN 包全量统计（包括接收/发送/重传）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(huatuo_bamai_netstat_container_Tcp_ActiveOpens{container_host=~\"$container_host\"}[30s])+rate(huatuo_bamai_netstat_container_Tcp_PassiveOpens{container_host=~\"$container_host\"}[30s])+rate(huatuo_bamai_netstat_container_TcpExt_ListenDrops{container_host=~\"$container_host\"}[30s])+rate(huatuo_bamai_netstat_container_TcpExt_TCPSynRetrans{container_host=~\"$container_host\"}[30s])",
     "legendFormat": "{{container_host}}"
    }
   ]
  }
 ]
}